package com.wizt.common.http

object URLProvider {

    private var base_url = "http://wizt.xyz/api/v1/"
//    private var base_url = "http://192.168.1.43:8000/api/v1/"

    val login = base_url + "login"
    val register = base_url + "register/"
    val facebook_login = base_url + "login/facebook/"
    val google_login = base_url + "login/google/"
    val resetpassword = base_url + "password/new/"
    val logout = base_url + "logout"
    val get_labels = base_url + "labels/"
    val get_trainobjs = base_url + "trains/"
    val get_label = base_url + "label/"
    val post_label = base_url + "labels/"
    val update_label = base_url + "labels/@/"
    val delete_label = base_url + "labels/@/"
    val delete_train = base_url + "trains/@/"
    val get_friends = base_url + "users/friends/?is_friend=true"
    val get_user_list = base_url + "users/friends/?is_friend=false&query=@"
    val get_friend_request_list = base_url + "users/friends/request/"
    val post_friend_request = base_url + "users/friends/request/"
    val update_friend_request = base_url + "users/friends/request/@/"
    val delete_friend_request = base_url + "users/friends/request/@/"
    val get_notification_list = base_url + "notifications/"
    val post_notification = base_url + "notifications/"
    val delete_all_notifications = base_url + "notifications/clear/"
    val delete_notification = base_url + "notifications/@/"
    val get_share_label_list = base_url + "share/labels/?me=true"
    val get_share_log_list = base_url + "share/labels/?me=false"
    val post_share_label = base_url + "share/labels/"
    val update_share_label = base_url + "share/labels/@/"
    val delete_share_label = base_url + "share/labels/@/"
    val get_plan_list = base_url + "plans/"
    val get_my_profile = base_url + "profile/"
    val get_my_address = base_url + "address/"
    val post_my_address = base_url + "address/"
    val post_subscribe = base_url + "subscriptions/"
    val post_checksubscribe = base_url + "stripe/checkSubscription"
    val get_floor_plan_list = base_url + "floorplans/"
    val post_floor_plan = base_url + "floorplans/"
    val delete_floor_plan = base_url + "floorplans/@/"
    val post_fybe_train = base_url + "trains/"
    val update_fybe_train = base_url + "trains/@/"

    val post_prediction_model = "http://13.250.228.166:5000/predict?user_id=@"
}